global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: node-exporter
    static_configs:
      - targets: ["svcNodeExporter:9100", "yoda:9100", "anton:9100"]
    relabel_configs:
      - source_labels: [__address__]
        regex: "svcNodeExporter:9100"
        target_label: instance
        replacement: talos
      - source_labels: [__address__]
        regex: "yoda:9100"
        target_label: instance
        replacement: yoda
      - source_labels: [__address__]
        regex: "anton:9100"
        target_label: instance
        replacement: anton

  - job_name: cadvisor
    static_configs:
      - targets: ["svccAdvisor:8080", "yoda:9101", "anton:9101"]
    relabel_configs:
      - source_labels: [__address__]
        regex: "svccAdvisor:8080"
        target_label: instance
        replacement: talos
      - source_labels: [__address__]
        regex: "yoda:9101"
        target_label: instance
        replacement: yoda
      - source_labels: [__address__]
        regex: "anton:9101"
        target_label: instance
        replacement: anton

  - job_name: smartctl
    static_configs:
      - targets: ["anton:9633"]
    relabel_configs:
      - source_labels: [__address__]
        regex: "anton:9633"
        target_label: instance
        replacement: anton
