include:
  - heimdall/compose.yaml
  - pihole/compose.yaml
  - nginx/compose.yaml
  - openclaw/compose.yaml
  - transmission/compose.yaml
  - prowlarr/compose.yaml
  - flaresolverr/compose.yaml
  - sonarr/compose.yaml
  - radarr/compose.yaml
  - jellyfin/compose.yaml
  - cadvisor/compose.yaml
  - node-exporter/compose.yaml
  - smartctl-exporter/compose.yaml
  - prometheus/compose.yaml
  - grafana/compose.yaml