services:
  # ==============================
  # Service: Pi-hole
  # ==============================
  svcPihole:
    container_name: pihole
    image: pihole/pihole:2025.04.0
    ports:
      - "53:53/tcp" # port DNS (TCP)
      - "53:53/udp" # prt DNS (UDP)
      - "8081:80" # ui
    environment:
      TZ: "America/Bogota" # time zone
      FTLCONF_webserver_api_password: ${PIHOLE_PASS}
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_dns_upstreams: '1.1.1.1;8.8.8.8;2606:4700:4700::1111;2001:4860:4860::8888'
    volumes:
      - /mnt/data/pihole/etc-pihole-v2:/etc/pihole # config
    restart: unless-stopped
  # ==============================
  # Service: Transmission
  # ==============================
  svcTransmission:
    container_name: transmission
    image: linuxserver/transmission:arm64v8-4.0.6
    ports:
      - 8082:9091         # ui
      - 51413:51413       # port (TCP)
      - 51413:51413/udp   # port (UDP)
    volumes:
      - /mnt/data/transmission/config:/config        # config
      - /mnt/data/transmission/downloads:/downloads # downloads
      - /mnt/data/transmission/watch:/watch        
    environment:
      - PUID=1000         # user id
      - PGID=1000         # group id
      - TZ=America/Bogota # tz
    restart: unless-stopped
  # ==============================
  # Service: Jackett
  # ==============================
  svcJackett:
    container_name: jackett
    image: linuxserver/jackett:arm64v8-0.22.1795
    ports:
      - 8083:9117         # ui
    volumes:
      - /mnt/data/jackett/config:/config # config
    environment:
      - PUID=1000         # user id
      - PGID=1000         # group id
      - TZ=America/Bogota # tz
    restart: unless-stopped