services:
  svcPihole:
    container_name: pihole
    image: pihole/pihole:2026.07.2
    profiles:
      - dns
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8085:80"   # Web admin (8082 en uso por Transmission)
    dns:
      - 9.9.9.9
      - 1.1.1.2
    volumes:
      - ${PATH_DATA}/persistence/pihole/etc-pihole-v2:/etc/pihole
      - ${PATH_DATA}/persistence/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    environment:
      TZ: "America/Bogota"
      WEBTHEME: "default-dark"
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_dns_upstreams: '9.9.9.9;1.1.1.2;2620:fe::fe;2606:4700:4700::1112'
      FTLCONF_maxlogage: "168"
      FTLCONF_maxlogsize: "50"
      FTLCONF_dns_cache_size: "20000"
      FTLCONF_dns_max_cache_ttl: "1800"
      FTLCONF_blockingmode: "NULL"
      FTLCONF_dns_edns0: "yes"
      FTLCONF_dns_check_aaaa: "yes"
      FTLCONF_dns_compress: "yes"
      FTLCONF_dns_prefetch: "yes"
      FTLCONF_dns_forward_max: "150"
