services:
  svcJellyfin:
    image: lscr.io/linuxserver/jellyfin:arm64v8-10.10.7
    container_name: jellyfin
    privileged: true
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    volumes:
      - "${PATH_DATA}/jellyfin/library:/config"
      - "${PATH_DATA}/media/tvseries:/data/tvshows"
      - "${PATH_DATA}/media/movies:/data/movies"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/vchiq:/dev/vchiq
    restart: unless-stopped
