services:
  svcProwlarr:
    image: lscr.io/linuxserver/prowlarr:arm64v8-nightly-1.34.1.5018-ls196
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    volumes:
      - "${PATH_DATA}/prowlarr:/config"
    ports:
      - 8083:9696
    restart: unless-stopped
