---
- name: Start pihole service
  shell: |
    cd /home/{{ ansible_user }}/services/homelab/services/docker
    PIHOLE_PASS={{ PIHOLE_PASS }} PATH_DATA={{ PATH_DATA }} docker compose --profile dns up -d