---
- name: System Initialization and Homelab Setup
  hosts: all
  become: true
  tasks:
    - name: Update and upgrade all packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600

    - name: Configure systemd-resolved (Free port 53)
      block:
        - name: Create DNS config directory
          ansible.builtin.file:
            path: /etc/systemd/resolved.conf.d
            state: directory
            mode: "0755"

        - name: Disable DNS stub listener
          ansible.builtin.copy:
            content: |
              [Resolve]
              DNSStubListener=no
            dest: /etc/systemd/resolved.conf.d/dns.conf
            owner: root
            group: root
            mode: "0644"
          notify: Restart systemd-resolved

    - name: Prepare user services directory
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/services"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

    - name: Download homelab code
      ansible.builtin.git:
        repo: "https://github.com/dcerbero/homelab.git"
        dest: "/home/{{ ansible_user }}/services/homelab"
        version: main
        force: yes
      become: true
      become_user: "{{ ansible_user }}" # Clonar con el usuario, no como root

  handlers:
    - name: Restart systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: restarted