---
- name: Add permissions for openclaw data directory
  ansible.builtin.file:
    path: "{{ PATH_DATA }}/ia/openclaw"
    state: directory
    owner: "1000"
    group: "1000"
    mode: '0755'
    recurse: yes
  become: true
- name: Start openclaw service
  shell: |
    cd /home/{{ ansible_user }}/services/homelab/services/docker
    PATH_DATA={{ PATH_DATA }} docker compose --profile ia up -d