---
- name: Add permissions for openclaw data directory
  ansible.builtin.file:
    path: "{{ PATH_DATA }}/persistence/openclaw"
    state: directory
    owner: "1000"
    group: "1000"
    mode: '0755'
    recurse: yes
- name: Start openclaw service
  ansible.builtin.shell: |
    cd {{ ansible_facts['env']['HOME'] }}/services/homelab/services/docker
    PATH_DATA={{ PATH_DATA }} docker compose --profile ia up -d
  register: openclaw_result
  changed_when: openclaw_result.stdout is search("Created|Started|Recreated")
