---
- name: Setup homeserver
  hosts: homeserver
  become: true
  
  roles:
    - role: system-setup
      tags: [system-setup, system]
    - role: docker
      tags: [docker, containers]
    - role: pihole
      tags: [pihole, dns]
    - role: tailscale
      tags: [tailscale, vpn]
    - role: cadvisor
      tags: [cadvisor, monitoring]
    - role: openclaw
      tags: [openclaw, ia]
    - role: headroom
      tags: [headroom, ia]
    - role: nginx
      tags: [nginx, proxy]