---
- name: Setup yoda
  hosts: yoda
  become: true
  gather_facts: no

  pre_tasks:
    - name: Gather facts as connection user
      ansible.builtin.setup:
      become: false
      tags: always

  roles:
    - role: system-setup
      tags: [system-setup, system]
    - role: docker
      tags: [docker, containers]
    - role: preflight
      tags: [preflight, containers, pihole, dns, cadvisor, monitoring, openclaw, ia, heimdall, dashboard, nginx, proxy]
    - role: systemd-resolved
      tags: [systemd-resolved, dns, system]
    - role: pihole
      tags: [pihole, dns]
    - role: tailscale
      tags: [tailscale, vpn]
    - role: cadvisor
      tags: [cadvisor, monitoring]
    - role: openclaw
      tags: [openclaw, ia]
    - role: heimdall
      tags: [heimdall, dashboard]
    - role: nginx
      tags: [nginx, proxy]

- name: Setup talos
  hosts: talos
  become: true
  gather_facts: no

  pre_tasks:
    - name: Gather facts as connection user
      ansible.builtin.setup:
      become: false
      tags: always

  roles:
    - role: system-setup
      tags: [system-setup, system, talos]
    - role: docker
      tags: [docker, containers, talos]
    - role: preflight
      tags: [preflight, containers, talos, pihole, dns, monitoring, metrics]
    - role: systemd-resolved
      tags: [systemd-resolved, dns, system, talos]
    - role: pihole
      tags: [pihole, dns, talos]
    - role: monitoring
      tags: [monitoring, metrics, talos]

- name: Setup anton
  hosts: anton
  become: true
  gather_facts: no

  pre_tasks:
    - name: Gather facts as connection user
      ansible.builtin.setup:
      become: false
      tags: always

  roles:
    - role: system-setup
      tags: [system-setup, system, anton]
    - role: docker
      tags: [docker, containers, anton]
    - role: preflight
      tags: [preflight, containers, anton, cadvisor, monitoring, smartctl, media, media-streaming, media-download]
    - role: cadvisor
      tags: [cadvisor, monitoring, anton]
    - role: smartctl
      tags: [smartctl, monitoring, anton]
    - role: tailscale
      tags: [tailscale, vpn, anton]
    - role: media
      tags: [media, media-streaming, media-download, anton]
